<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [3]:
def matrix_mul(A, B):
    mat=[]
    for i in A:
        p=i
        temp=[]
        for k in range(len(B[0])):
            res=0
            i=0
            for j in range(len(p)):
                res=res+(p[j]*B[i][k])
                i+=1
            temp.append(res)
        mat.append(temp) 
    return mat 
A   = [[1,2],[3,4]]
B   = [[1,2 ,3, 4, 5],[5, 6 ,7 ,8, 9]]
if ((len([A][0]))==(len(B))):              #checks the condition for matrix multiplication
          print(matrix_mul(A,B))
else:
    print("matrix multiplication is not posiible")

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [7]:
from random import uniform
def pick_a_number_from_list(A):
    sum=0
    for i in A:
        sum=sum+i            #finding total sum of given magnitudes
    temp=[]
    for i in range(len(A)):
        temp.append(A[i]/sum)  #normalizing using sum
    temp2=[]
    temp2.append(temp[0])
    for i in range(1,len(A)):
        temp2.append(temp2[i-1]+temp[i]) #cummulative sum
    r=uniform(0.0,1.0)      
    counter=0
    #proportional sampling
    for i in temp2:
        if r<i:
            break
        else:
            counter+=1
    return A[counter]
A=[1.0,2.8,3.2,4,10]
def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
sampling_based_on_magnitued()

4
10
4
4
10
2.8
4
3.2
4
10
10
10
10
10
10
4
4
10
3.2
10
10
10
4
10
10
1.0
4
4
10
3.2
10
10
10
10
10
2.8
10
3.2
2.8
10
4
1.0
4
10
4
3.2
4
10
10
10
10
3.2
10
10
10
3.2
2.8
10
1.0
1.0
3.2
2.8
10
4
2.8
4
10
10
4
10
4
4
10
10
10
2.8
4
4
10
4
4
4
1.0
4
3.2
10
10
10
3.2
3.2
2.8
10
10
10
10
3.2
10
10
4


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [8]:
def replace_digits(String):
    # write your code
    s=""
    g="#"
    for i in String:
        if i.isdigit():
            s=s+g        #replacing digits with "#"
    return s 
String=input("enter alphanumeric value : ")
replace_digits(String)

enter alphanumeric value : #2a$#b%c%561#


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
def display_dash_board(students, marks):
    dict={}
    count=0
    top_5_students=[]
    least_5_students=[]
    students_within_25_and_75=[]
    #creating a dictionary with students and marks
    for i in students:
        dict[i]=marks[count]
        count+=1
    #sorting dictionary
    dict1 = sorted(dict.items(),key=lambda x: x[1])
    #for least 5 students
    for i in range(5):
        least_5_students.append(dict1[i])
    #for top 5 students
    for i in range(1,6):
        top_5_students.append(dict1[(len(dict)-i)])
    #calculating 25th and 75th percentile
    p_25=len(dict)//4
    p_75=int((len(dict)*(3/4)))
    # list for marks within 25th and 75th percentile
    for i in dict1[p_25:p_75]:
        students_within_25_and_75.append(i)
    return top_5_students, least_5_students, students_within_25_and_75
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print("top 5 stundents and their marks are:")
print(top_5_students)
print("leasr 5 students and their marks are:")
print(least_5_students)
print("students with 25th and 75th percentile are:")
print(students_within_25_and_75)

top 5 stundents and their marks are:
[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
leasr 5 students and their marks are:
[('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
students with 25th and 75th percentile are:
[('student9', 35), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [31]:
import math

def closest_points_to_p(S, P):
    S.sort(key=lambda x: math.acos(((x[0]*p[0])+(x[1]*p[1]))/
                                  ((math.sqrt((x[0]**2)+(x[1]**2)))*(math.sqrt((p[0]**2)+(p[1]**2))))))
    return S  # its list of tuples
p=(3,-4)
s = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
points = closest_points_to_p(s, p)
print(points[:5])


[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [28]:
import math
def i_am_the_one(red,blue,line):
    x,s=line.split("x")
    y,z=s.split("y")
    x=float(x) # x coeffient
    z=-float(z) 
    g=float(y) # y coeffient
    count1=0
    count2=0
    for i in red:
        equation=((x*i[0])+(g*i[1]))
        if equation>z:
            count1+=1
        else:
            count2+=1
    count3=0
    count4=0
    if (count1 ==len(red) or count2==len(red)):
        for j in blue:
            equation1=((x*j[0])+(g*j[1]))
            if equation1<z:
                count3+=1
            else:
                count4+=1
    if count1==count3 or count2==count4:
        return "YES"
    else:
        return "NO"
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [2]:
def curve_smoothing(string):
    flag="true"
    s=str(string).split(",")
    temp=[]
    temp1=[]
    counter=0
    index=[]
    z=0
    li=[]
    total_parts=0
    total=0
    if (s[0]=="_" and s[-1]!="_") or (s[0]!="_" and s[-1]=="_"):
        for m in s:
            if m=="_":
                counter+=1
            else:
                temp.append(m)
        total_parts=float(temp[0])/len(s)
        for m in range(len(s)):
            s[m]=total_parts
    elif (s[0]!="_" and s[-1]!="_"):
        for t in s:
            if t=="_":
                counter+=1
            else:
                temp.append(t)
        for t in temp:
            total+=float(t)
            total_parts=total/len(s)
        for m in range(len(s)):
            s[m]=total_parts
    else:
        while flag=="true":
           if "_" in s:
               for i in range(z,len(s)):
                    if s[i]=="_":
                        counter+=1
                        index.append(i)
                    else:
                        temp1.append(s[i])
                        li.append(i)
                        z=i+1
                        break
        
               if counter>0:
                    if (len(temp1)==1):
                        total=float(temp1[0])
                        total_parts=(total)/(counter+1)
                    else:
                        total=0
                        for i in temp1:
                            total+=float(i)
                        total_parts=total/(counter+2)
                    for g in index:
                        s[g]=total_parts
           if "_" not in s:
                flag="false"
           temp1.clear()
           temp1.append(total_parts)
           counter=0
           index.clear()
        for h in li:
            if h!=0 or h!=len(s):
                s[h]=s[h+1]
    return s
                        
        
q=["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]
for r in q:
    u=curve_smoothing(r)
    print(u)



[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [60]:
def compute_conditional_probabilites(A):
    list=['F1','F2','F3','F4','F5']
    list1=['S1','S2','S3']
    for i in list:
        for j in list1:
            count1=0
            count2=0
            for k in A:
                if k[0]==i and k[1]==j:
                    count1+=1
                if k[1]==j:
                    count2+=1
            print("P(F=F1|S==S1)={}/{}".format(count1,count2),end=",")
        print("\n")
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)


P(F=F1|S==S1)=1/4,P(F=F1|S==S1)=1/3,P(F=F1|S==S1)=0/3,

P(F=F1|S==S1)=1/4,P(F=F1|S==S1)=1/3,P(F=F1|S==S1)=1/3,

P(F=F1|S==S1)=0/4,P(F=F1|S==S1)=1/3,P(F=F1|S==S1)=1/3,

P(F=F1|S==S1)=1/4,P(F=F1|S==S1)=0/3,P(F=F1|S==S1)=1/3,

P(F=F1|S==S1)=1/4,P(F=F1|S==S1)=0/3,P(F=F1|S==S1)=0/3,



<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [5]:
def string_features(S1, S2):
    #spliting the words
    set1=S1.split(" ")
    set2=S2.split(" ")
    #converting to set
    set1=set(set1)      #typecasting
    set2=set(set2)      #typecasting
    common_words=set1.intersection(set2) #finding common words 
    a=len(common_words)            #number of common words in given two sentences
    b=set1-set2                    #Words in S1 but not in S2
    c=set2-set1                    #Words in S2 but not in S1

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a.{}".format(a))
print("b.{}".format(b))
print("c.{}".format(c))

a.7
b.{'F', 'first', '5'}
c.{'3', 'second', 'S'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [47]:
def compute_log_loss(A):
    s=0
    for i in A:
        s=s+(i[0]*math.log10(i[1]))+(((1-i[0])*math.log10(1-i[1])))
    loss=(-1/len(A))*s
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
